[package]
name = "Evoris"
version = "0.1.0"
description = "Evoris — a fully offline, encrypted, open-source password manager."
authors = ["Muhammad Hassan"]
license = "MIT"
repository = "https://github.com/miangee21/evoris"
edition = "2021"

[lib]
name = "evoris_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-dialog = "2.7.3"
tauri-plugin-fs = "2.5.2"
tauri-plugin-clipboard-manager = "2.3.3"
tauri-plugin-os = "2.3.2"
aes-gcm = { version = "0.11.1", features = ["aes", "alloc"] }
zeroize = { version = "1.9.0", features = ["derive"] }
thiserror = "2.0.20"
uuid = { version = "1.26.1", features = ["v4", "serde"] }
base32 = "0.5.1"
argon2 = "0.6.0"
rand_core = "0.10.1"
getrandom = "0.4.3"

[profile.release]
panic = "abort"
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[lints.rust]
unsafe_code = "deny"
