//src/features/categories/constants/category-icons.ts
import {
  FolderIcon,
  WalletIcon,
  KeyIcon,
  GlobeIcon,
  BriefcaseIcon,
  HeartIcon,
  PlaneIcon,
  CarIcon,
  HomeIcon,
  ShoppingCartIcon,
  MusicIcon,
  ImageIcon,
  FileTextIcon,
  CodeIcon,
  GamepadIcon,
  CoffeeIcon,
  GiftIcon,
  BookIcon,
  CameraIcon,
  VideoIcon,
  BellIcon,
  StarIcon,
  ShieldIcon,
  LockIcon,
  SmartphoneIcon,
  MonitorIcon,
  CpuIcon,
  FingerprintIcon,
  MapIcon,
  UmbrellaIcon,
  CircleHelpIcon,
  type LucideIcon,
} from "lucide-react";

export const CATEGORY_ICONS: Record<string, LucideIcon> = {
  folder: FolderIcon,
  wallet: WalletIcon,
  key: KeyIcon,
  globe: GlobeIcon,
  briefcase: BriefcaseIcon,
  heart: HeartIcon,
  plane: PlaneIcon,
  car: CarIcon,
  home: HomeIcon,
  shopping_cart: ShoppingCartIcon,
  music: MusicIcon,
  image: ImageIcon,
  file_text: FileTextIcon,
  code: CodeIcon,
  gamepad: GamepadIcon,
  coffee: CoffeeIcon,
  gift: GiftIcon,
  book: BookIcon,
  camera: CameraIcon,
  video: VideoIcon,
  bell: BellIcon,
  star: StarIcon,
  shield: ShieldIcon,
  lock: LockIcon,
  smartphone: SmartphoneIcon,
  monitor: MonitorIcon,
  cpu: CpuIcon,
  fingerprint: FingerprintIcon,
  map: MapIcon,
  umbrella: UmbrellaIcon,
};

// Fallback if an icon is removed from lucide-react in the future
export const FALLBACK_ICON = CircleHelpIcon;
